services:
  # API Service
  - type: web
    name: esus-audit-ai-api
    env: node
    plan: standard
    buildCommand: cd server && npm install && npm run build
    startCommand: cd server && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: AZURE_FORM_RECOGNIZER_KEY
        sync: false
      - key: AZURE_FORM_RECOGNIZER_ENDPOINT
        sync: false
      - key: AZURE_OPENAI_ENDPOINT
        sync: false
      - key: AZURE_OPENAI_API_KEY
        sync: false
      - key: AZURE_SEARCH_ENDPOINT
        sync: false
      - key: AZURE_SEARCH_API_KEY
        sync: false
      - key: APPLICATIONINSIGHTS_CONNECTION_STRING
        sync: false
      - key: MAX_FILE_SIZE
        value: 52428800
      - key: ALLOWED_ORIGINS
        value: https://app.esusaudit.ai
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100

  # Frontend Service  
  - type: web
    name: esus-audit-ai-web
    env: node
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/dist
    envVars:
      - key: VITE_API_URL
        value: https://api.esusaudit.ai
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false